from __future__ import annotations

import json
import time
from pathlib import Path
from urllib.parse import urlparse

import httpx

from core.generation.adapters.common import AdapterContext, AdapterExecutionResult, GeneratedArtifact
from core.models.schemas import Modality


def adapter_name() -> str:
    return "ace-step"


def execute(context: AdapterContext) -> AdapterExecutionResult:
    if not context.health_check:
        raise RuntimeError("ACE-Step health check URL is missing.")
    base_url = context.health_check.removesuffix("/health").rstrip("/")
    payload = {
        "prompt": context.job.prompt,
        "global_caption": context.job.summary,
        "lyrics": "",
        "thinking": False,
        "sample_mode": False,
        "use_format": False,
        "inference_steps": 8,
        "guidance_scale": 7.0,
        "use_random_seed": True,
        "seed": -1,
        "task_type": "text2music",
        "audio_format": "wav",
    }

    with httpx.Client(timeout=120.0) as client:
        if context.report_progress:
            context.report_progress(15, "Submitting ACE-Step task")
        response = client.post(f"{base_url}/release_task", json=payload)
        response.raise_for_status()
        body = response.json()
        task_id = str((body.get("data") or {}).get("task_id") or "")
        if not task_id:
            raise RuntimeError("ACE-Step did not return a task id.")

        result_item = _poll_result(client, base_url, task_id, context)
        file_url = str(result_item.get("file") or "")
        if not file_url:
            raise RuntimeError("ACE-Step completed without an audio file.")
        if file_url.startswith("/"):
            file_url = f"{base_url}{file_url}"
        file_response = client.get(file_url)
        file_response.raise_for_status()
        suffix = Path(urlparse(file_url).path).suffix or ".wav"

    artifact = GeneratedArtifact(
        modality=Modality.MUSIC,
        asset_type="music",
        title=context.job.title,
        filename=f"{context.job.project_id}-{context.job.id[:8]}{suffix}",
        description="Generated by ACE-Step.",
        content=file_response.content,
    )
    return AdapterExecutionResult(artifacts=[artifact], metadata={"backend": "ace-step", "task_id": task_id})


def _poll_result(client: httpx.Client, base_url: str, task_id: str, context: AdapterContext) -> dict:
    for attempt in range(180):
        response = client.post(f"{base_url}/query_result", json={"task_id_list": [task_id]})
        response.raise_for_status()
        payload = response.json()
        items = (payload.get("data") or [])
        if not items:
            time.sleep(1)
            continue
        item = items[0]
        status = int(item.get("status") or 0)
        progress_text = str(item.get("progress_text") or "").strip()
        if context.report_progress:
            context.report_progress(min(90, 20 + attempt // 2), progress_text or "Waiting for ACE-Step")
        result_raw = item.get("result") or "[]"
        try:
            result_items = json.loads(result_raw)
        except json.JSONDecodeError:
            result_items = []
        first_result = result_items[0] if result_items and isinstance(result_items[0], dict) else {}
        if status == 1:
            return first_result
        if status == 2:
            raise RuntimeError(str(first_result.get("error") or progress_text or "ACE-Step generation failed."))
        time.sleep(2)
    raise RuntimeError("ACE-Step did not finish within the expected timeout.")
