from __future__ import annotations

import time
import uuid
from pathlib import Path
from urllib.parse import urlencode

import httpx

from core.generation.adapters.common import AdapterContext, AdapterExecutionResult, GeneratedArtifact
from core.models.schemas import GenerationRecipe, Modality

DEFAULT_NEGATIVE_PROMPT = "low quality, blurry, deformed, extra limbs, bad anatomy"


def adapter_name() -> str:
    return "comfyui"


def execute(context: AdapterContext) -> AdapterExecutionResult:
    base_url = _resolve_base_url(context.health_check)
    checkpoint_name = _resolve_checkpoint_name(context.worker_path)
    prompt_id = uuid.uuid4().hex
    filename_prefix = f"misaka-{context.job.project_id}-{context.job.id[:8]}"

    with httpx.Client(timeout=60.0) as client:
        recipe = _resolve_recipe(context)
        if context.report_progress:
            context.report_progress(10, f"Preparing {recipe.value} workflow")
        workflow = _build_workflow(
            recipe=recipe,
            client=client,
            base_url=base_url,
            checkpoint_name=checkpoint_name,
            positive_prompt=context.job.prompt,
            negative_prompt=DEFAULT_NEGATIVE_PROMPT,
            filename_prefix=filename_prefix,
            seed=_stable_seed(prompt_id),
            source_asset_path=context.source_asset_path,
            mask_asset_path=context.mask_asset_path,
        )
        if context.report_progress:
            context.report_progress(35, "Submitting workflow to ComfyUI")
        response = client.post(
            f"{base_url}/prompt",
            json={
                "prompt": workflow,
                "client_id": f"misaka-{context.job.project_id}",
                "prompt_id": prompt_id,
            },
        )
        response.raise_for_status()

        history = _wait_for_history(client, base_url, prompt_id, context)
        images = _download_output_images(client, base_url, history)

    if not images:
        raise RuntimeError("ComfyUI finished without returning any generated images.")

    artifacts: list[GeneratedArtifact] = []
    for index, image in enumerate(images, start=1):
        suffix = Path(image["filename"]).suffix or ".png"
        artifacts.append(
            GeneratedArtifact(
                modality=Modality.IMAGE,
                asset_type="image",
                title=context.job.title if index == 1 else f"{context.job.title} #{index}",
                filename=f"{filename_prefix}-{index}{suffix}",
                description=f"Generated by ComfyUI with checkpoint {checkpoint_name}.",
                content=image["content"],
            )
        )
    return AdapterExecutionResult(artifacts=artifacts, metadata={"prompt_id": prompt_id, "checkpoint": checkpoint_name})


def _resolve_recipe(context: AdapterContext) -> GenerationRecipe:
    recipe = context.job.recipe or GenerationRecipe.AUTO
    if recipe is GenerationRecipe.AUTO:
        if context.source_asset_path and context.mask_asset_path:
            return GenerationRecipe.INPAINT
        if context.source_asset_path:
            return GenerationRecipe.IMG2IMG
        return GenerationRecipe.TXT2IMG
    return recipe


def _resolve_base_url(health_check: str | None) -> str:
    if not health_check:
        raise RuntimeError("ComfyUI health check URL is missing.")
    return health_check.removesuffix("/system_stats").rstrip("/")


def _resolve_checkpoint_name(worker_path: Path) -> str:
    checkpoint_dir = worker_path / "models" / "checkpoints"
    checkpoint_files = sorted(
        item.name
        for item in checkpoint_dir.glob("*")
        if item.is_file() and item.name != "put_checkpoints_here"
    )
    if not checkpoint_files:
        raise RuntimeError("ComfyUI has no installed checkpoint.")
    return checkpoint_files[0]


def _build_workflow(
    *,
    recipe: GenerationRecipe,
    client: httpx.Client,
    base_url: str,
    checkpoint_name: str,
    positive_prompt: str,
    negative_prompt: str,
    filename_prefix: str,
    seed: int,
    source_asset_path: Path | None,
    mask_asset_path: Path | None,
) -> dict[str, dict]:
    if recipe is GenerationRecipe.IMG2IMG:
        if source_asset_path is None:
            raise RuntimeError("img2img requires a source image asset.")
        source_name = _upload_input_asset(client, base_url, source_asset_path)
        return {
            "3": {
                "class_type": "KSampler",
                "inputs": {
                    "cfg": 7,
                    "denoise": 0.45,
                    "latent_image": ["11", 0],
                    "model": ["4", 0],
                    "negative": ["7", 0],
                    "positive": ["6", 0],
                    "sampler_name": "euler",
                    "scheduler": "normal",
                    "seed": seed,
                    "steps": 24,
                },
            },
            "4": {
                "class_type": "CheckpointLoaderSimple",
                "inputs": {"ckpt_name": checkpoint_name},
            },
            "6": {
                "class_type": "CLIPTextEncode",
                "inputs": {"clip": ["4", 1], "text": positive_prompt},
            },
            "7": {
                "class_type": "CLIPTextEncode",
                "inputs": {"clip": ["4", 1], "text": negative_prompt},
            },
            "10": {
                "class_type": "LoadImage",
                "inputs": {"image": source_name},
            },
            "11": {
                "class_type": "VAEEncode",
                "inputs": {"pixels": ["10", 0], "vae": ["4", 2]},
            },
            "8": {
                "class_type": "VAEDecode",
                "inputs": {"samples": ["3", 0], "vae": ["4", 2]},
            },
            "9": {
                "class_type": "SaveImage",
                "inputs": {"filename_prefix": filename_prefix, "images": ["8", 0]},
            },
        }
    if recipe is GenerationRecipe.INPAINT:
        if source_asset_path is None or mask_asset_path is None:
            raise RuntimeError("inpaint requires both source and mask assets.")
        source_name = _upload_input_asset(client, base_url, source_asset_path)
        mask_name = _upload_input_asset(client, base_url, mask_asset_path)
        return {
            "3": {
                "class_type": "KSampler",
                "inputs": {
                    "cfg": 7,
                    "denoise": 0.65,
                    "latent_image": ["13", 2],
                    "model": ["4", 0],
                    "negative": ["13", 1],
                    "positive": ["13", 0],
                    "sampler_name": "euler",
                    "scheduler": "normal",
                    "seed": seed,
                    "steps": 28,
                },
            },
            "4": {
                "class_type": "CheckpointLoaderSimple",
                "inputs": {"ckpt_name": checkpoint_name},
            },
            "6": {
                "class_type": "CLIPTextEncode",
                "inputs": {"clip": ["4", 1], "text": positive_prompt},
            },
            "7": {
                "class_type": "CLIPTextEncode",
                "inputs": {"clip": ["4", 1], "text": negative_prompt},
            },
            "10": {
                "class_type": "LoadImage",
                "inputs": {"image": source_name},
            },
            "11": {
                "class_type": "LoadImageMask",
                "inputs": {"image": mask_name, "channel": "alpha"},
            },
            "13": {
                "class_type": "InpaintModelConditioning",
                "inputs": {
                    "positive": ["6", 0],
                    "negative": ["7", 0],
                    "vae": ["4", 2],
                    "pixels": ["10", 0],
                    "mask": ["11", 0],
                },
            },
            "8": {
                "class_type": "VAEDecode",
                "inputs": {"samples": ["3", 0], "vae": ["4", 2]},
            },
            "9": {
                "class_type": "SaveImage",
                "inputs": {"filename_prefix": filename_prefix, "images": ["8", 0]},
            },
        }
    return {
        "3": {
            "class_type": "KSampler",
            "inputs": {
                "cfg": 7,
                "denoise": 1,
                "latent_image": ["5", 0],
                "model": ["4", 0],
                "negative": ["7", 0],
                "positive": ["6", 0],
                "sampler_name": "euler",
                "scheduler": "normal",
                "seed": seed,
                "steps": 24,
            },
        },
        "4": {
            "class_type": "CheckpointLoaderSimple",
            "inputs": {
                "ckpt_name": checkpoint_name,
            },
        },
        "5": {
            "class_type": "EmptyLatentImage",
            "inputs": {
                "batch_size": 1,
                "height": 1024,
                "width": 768,
            },
        },
        "6": {
            "class_type": "CLIPTextEncode",
            "inputs": {
                "clip": ["4", 1],
                "text": positive_prompt,
            },
        },
        "7": {
            "class_type": "CLIPTextEncode",
            "inputs": {
                "clip": ["4", 1],
                "text": negative_prompt,
            },
        },
        "8": {
            "class_type": "VAEDecode",
            "inputs": {
                "samples": ["3", 0],
                "vae": ["4", 2],
            },
        },
        "9": {
            "class_type": "SaveImage",
            "inputs": {
                "filename_prefix": filename_prefix,
                "images": ["8", 0],
            },
        },
    }


def _stable_seed(prompt_id: str) -> int:
    return int(prompt_id[:8], 16)


def _upload_input_asset(client: httpx.Client, base_url: str, asset_path: Path) -> str:
    with asset_path.open("rb") as file_handle:
        response = client.post(
            f"{base_url}/upload/image",
            files={"image": (asset_path.name, file_handle, "application/octet-stream")},
            data={"type": "input", "overwrite": "true"},
        )
    response.raise_for_status()
    payload = response.json()
    return str(payload.get("name") or asset_path.name)


def _wait_for_history(client: httpx.Client, base_url: str, prompt_id: str, context: AdapterContext) -> dict:
    for _ in range(120):
        response = client.get(f"{base_url}/history/{prompt_id}")
        response.raise_for_status()
        payload = response.json()
        history = payload.get(prompt_id)
        if history and history.get("outputs"):
            if context.report_progress:
                context.report_progress(85, "Downloading generated images")
            return history
        time.sleep(1)
    raise RuntimeError("ComfyUI did not finish within the expected timeout.")


def _download_output_images(client: httpx.Client, base_url: str, history: dict) -> list[dict[str, bytes | str]]:
    output_images: list[dict[str, bytes | str]] = []
    outputs = history.get("outputs") or {}
    for node_output in outputs.values():
        for image in node_output.get("images", []):
            query = urlencode(
                {
                    "filename": str(image.get("filename") or ""),
                    "subfolder": str(image.get("subfolder") or ""),
                    "type": str(image.get("type") or "output"),
                }
            )
            response = client.get(f"{base_url}/view?{query}")
            response.raise_for_status()
            output_images.append({"filename": str(image.get("filename") or "output.png"), "content": response.content})
    return output_images
