from __future__ import annotations

import logging
import time
import uuid
from pathlib import Path
from urllib.parse import urlencode

import httpx

from core.config import get_settings
from core.generation.adapters.common import AdapterContext, AdapterExecutionResult, GeneratedArtifact
from core.models.schemas import GenerationRecipe, Modality

logger = logging.getLogger("misaka.generation.adapters.comfyui")

DEFAULT_NEGATIVE_PROMPT = "low quality, blurry, deformed, extra limbs, bad anatomy"


def adapter_name() -> str:
    return "comfyui"


def execute(context: AdapterContext) -> AdapterExecutionResult:
    base_url = _resolve_base_url(context.health_check)
    params = context.job.params or {}
    checkpoint_name = _resolve_checkpoint_name(
        context.worker_path,
        base_url=base_url,
        override=params.get("checkpoint") or params.get("ckpt_name"),
        default=get_settings().misaka_comfyui_default_checkpoint,
    )
    prompt_id = uuid.uuid4().hex
    filename_prefix = f"misaka-{context.job.project_id}-{context.job.id[:8]}"

    with httpx.Client(timeout=60.0) as client:
        recipe = _resolve_recipe(context)
        if context.report_progress:
            context.report_progress(10, f"Preparing {recipe.value} workflow")
        workflow = _build_workflow(
            recipe=recipe,
            client=client,
            base_url=base_url,
            checkpoint_name=checkpoint_name,
            positive_prompt=context.job.prompt,
            negative_prompt=DEFAULT_NEGATIVE_PROMPT,
            filename_prefix=filename_prefix,
            seed=_resolve_seed(context.job.params, prompt_id),
            params=context.job.params or {},
            source_asset_path=context.source_asset_path,
            mask_asset_path=context.mask_asset_path,
        )
        if context.report_progress:
            context.report_progress(35, "Submitting workflow to ComfyUI")
        response = client.post(
            f"{base_url}/prompt",
            json={
                "prompt": workflow,
                "client_id": f"misaka-{context.job.project_id}",
                "prompt_id": prompt_id,
            },
        )
        response.raise_for_status()

        history = _wait_for_history(client, base_url, prompt_id, context)
        images = _download_output_images(client, base_url, history)

    if not images:
        raise RuntimeError("ComfyUI finished without returning any generated images.")

    artifacts: list[GeneratedArtifact] = []
    for index, image in enumerate(images, start=1):
        suffix = Path(image["filename"]).suffix or ".png"
        artifacts.append(
            GeneratedArtifact(
                modality=Modality.IMAGE,
                asset_type="image",
                title=context.job.title if index == 1 else f"{context.job.title} #{index}",
                filename=f"{filename_prefix}-{index}{suffix}",
                description=f"Generated by ComfyUI with checkpoint {checkpoint_name}.",
                content=image["content"],
            )
        )
    return AdapterExecutionResult(artifacts=artifacts, metadata={"prompt_id": prompt_id, "checkpoint": checkpoint_name})


def _resolve_recipe(context: AdapterContext) -> GenerationRecipe:
    recipe = context.job.recipe or GenerationRecipe.AUTO
    if recipe is GenerationRecipe.AUTO:
        if context.source_asset_path and context.mask_asset_path:
            return GenerationRecipe.INPAINT
        if context.source_asset_path:
            return GenerationRecipe.IMG2IMG
        return GenerationRecipe.TXT2IMG
    return recipe


def _resolve_base_url(health_check: str | None) -> str:
    if not health_check:
        raise RuntimeError("ComfyUI health check URL is missing.")
    return health_check.removesuffix("/system_stats").rstrip("/")


def fetch_live_checkpoints(base_url: str, *, timeout: float = 2.0) -> list[str]:
    """Query a running ComfyUI for the checkpoints it can actually load
    (spec §5.13 live-first readiness). Reads
    ``GET <base>/object_info/CheckpointLoaderSimple`` and returns the
    ``ckpt_name`` enum the live server advertises -- this covers checkpoints
    placed outside ``workers/comfyui`` via ``extra_model_paths``. Returns an
    empty list (never raises) when the server is unreachable or the response
    is malformed, so callers can fall back to the local filesystem."""
    try:
        response = httpx.get(f"{base_url}/object_info/CheckpointLoaderSimple", timeout=timeout)
        response.raise_for_status()
        payload = response.json()
    except (httpx.HTTPError, ValueError):
        return []
    node = payload.get("CheckpointLoaderSimple") if isinstance(payload, dict) else None
    if not isinstance(node, dict):
        return []
    required = (node.get("input") or {}).get("required") or {}
    ckpt_spec = required.get("ckpt_name")
    # ComfyUI advertises enum inputs as ``[[option, ...], {meta}]`` or ``[[option, ...]]``.
    if not isinstance(ckpt_spec, (list, tuple)) or not ckpt_spec:
        return []
    options = ckpt_spec[0]
    if not isinstance(options, (list, tuple)):
        return []
    return sorted(str(item) for item in options if str(item).strip())


def _list_local_checkpoints(worker_path: Path) -> list[str]:
    checkpoint_dir = worker_path / "models" / "checkpoints"
    return sorted(
        item.name
        for item in checkpoint_dir.glob("*")
        if item.is_file() and item.name != "put_checkpoints_here"
    )


def _resolve_checkpoint_name(
    worker_path: Path,
    *,
    base_url: str | None = None,
    override: str | None = None,
    default: str | None = None,
) -> str:
    """Pick the checkpoint name for a workflow (spec §6.2 / BP-COMFY resolution
    order). Precedence:

    1. ``override`` — an explicit ``checkpoint``/``ckpt_name`` carried on the
       job/refine ``params`` (a user PATCH or a refine plan), honoured if it
       is actually installed (live server first, then local filesystem).
    2. ``default`` — the configured default checkpoint
       (``MISAKA_COMFYUI_DEFAULT_CHECKPOINT``), honoured only if it is present
       in the *live* server's advertised checkpoint list; if the live server
       is reachable but does not have it, a warning is logged and resolution
       falls through to the next rung rather than raising.
    3. ``live[0]`` — the live server's sorted-first checkpoint (existing
       behaviour, spec §5.13 live-first readiness).
    4. ``local[0]`` — the local filesystem listing, when the live server is
       unreachable or advertises nothing.
    """
    live = fetch_live_checkpoints(base_url) if base_url else []
    if override and override in live:
        return override
    if override and override in _list_local_checkpoints(worker_path):
        return override
    if default:
        if default in live:
            return default
        logger.warning(
            "Configured default checkpoint %r not found in the live ComfyUI "
            "checkpoint list; falling back to the live/local first entry.",
            default,
        )
    if live:
        return live[0]
    local = _list_local_checkpoints(worker_path)
    if local:
        return local[0]
    raise RuntimeError("ComfyUI has no installed checkpoint.")


def _sampler_inputs(
    *,
    params: dict,
    seed: int,
    default_denoise: float,
    default_steps: int,
    latent_ref: list,
    model_ref: list,
    positive_ref: list,
    negative_ref: list,
) -> dict:
    """Build a KSampler ``inputs`` block, applying §6.2 tunable params on top
    of recipe defaults. Unknown / absent params fall back to the defaults so
    the workflow graph is always well-formed."""
    return {
        "cfg": params.get("cfg", 7),
        "denoise": params.get("denoise", default_denoise),
        "latent_image": latent_ref,
        "model": model_ref,
        "negative": negative_ref,
        "positive": positive_ref,
        "sampler_name": params.get("sampler_name") or params.get("sampler") or "euler",
        "scheduler": params.get("scheduler", "normal"),
        "seed": seed,
        "steps": params.get("steps", default_steps),
    }


def _build_workflow(
    *,
    recipe: GenerationRecipe,
    client: httpx.Client,
    base_url: str,
    checkpoint_name: str,
    positive_prompt: str,
    negative_prompt: str,
    filename_prefix: str,
    seed: int,
    params: dict | None = None,
    source_asset_path: Path | None,
    mask_asset_path: Path | None,
) -> dict[str, dict]:
    params = params or {}
    if recipe is GenerationRecipe.IMG2IMG:
        if source_asset_path is None:
            raise RuntimeError("img2img requires a source image asset.")
        source_name = _upload_input_asset(client, base_url, source_asset_path)
        return {
            "3": {
                "class_type": "KSampler",
                "inputs": _sampler_inputs(
                    params=params,
                    seed=seed,
                    default_denoise=0.45,
                    default_steps=24,
                    latent_ref=["11", 0],
                    model_ref=["4", 0],
                    positive_ref=["6", 0],
                    negative_ref=["7", 0],
                ),
            },
            "4": {
                "class_type": "CheckpointLoaderSimple",
                "inputs": {"ckpt_name": checkpoint_name},
            },
            "6": {
                "class_type": "CLIPTextEncode",
                "inputs": {"clip": ["4", 1], "text": positive_prompt},
            },
            "7": {
                "class_type": "CLIPTextEncode",
                "inputs": {"clip": ["4", 1], "text": negative_prompt},
            },
            "10": {
                "class_type": "LoadImage",
                "inputs": {"image": source_name},
            },
            "11": {
                "class_type": "VAEEncode",
                "inputs": {"pixels": ["10", 0], "vae": ["4", 2]},
            },
            "8": {
                "class_type": "VAEDecode",
                "inputs": {"samples": ["3", 0], "vae": ["4", 2]},
            },
            "9": {
                "class_type": "SaveImage",
                "inputs": {"filename_prefix": filename_prefix, "images": ["8", 0]},
            },
        }
    if recipe is GenerationRecipe.INPAINT:
        if source_asset_path is None or mask_asset_path is None:
            raise RuntimeError("inpaint requires both source and mask assets.")
        source_name = _upload_input_asset(client, base_url, source_asset_path)
        # The mask is a standalone image asset (not an alpha edit of the source),
        # so it is uploaded as a normal input and read by ``LoadImageMask`` from
        # its alpha/grayscale channel. ComfyUI's ``/upload/mask`` endpoint instead
        # composites a mask into an *existing* image's alpha and requires an
        # ``original_ref``; that path does not fit a separate-mask-asset flow.
        mask_name = _upload_input_asset(client, base_url, mask_asset_path)
        return {
            "3": {
                "class_type": "KSampler",
                "inputs": _sampler_inputs(
                    params=params,
                    seed=seed,
                    default_denoise=0.65,
                    default_steps=28,
                    latent_ref=["13", 2],
                    model_ref=["4", 0],
                    positive_ref=["13", 0],
                    negative_ref=["13", 1],
                ),
            },
            "4": {
                "class_type": "CheckpointLoaderSimple",
                "inputs": {"ckpt_name": checkpoint_name},
            },
            "6": {
                "class_type": "CLIPTextEncode",
                "inputs": {"clip": ["4", 1], "text": positive_prompt},
            },
            "7": {
                "class_type": "CLIPTextEncode",
                "inputs": {"clip": ["4", 1], "text": negative_prompt},
            },
            "10": {
                "class_type": "LoadImage",
                "inputs": {"image": source_name},
            },
            "11": {
                # Read the mask from the red channel: a standalone white-on-black
                # mask (RGB or grayscale, no alpha) marks the edit region in white.
                "class_type": "LoadImageMask",
                "inputs": {"image": mask_name, "channel": "red"},
            },
            "13": {
                "class_type": "InpaintModelConditioning",
                "inputs": {
                    "positive": ["6", 0],
                    "negative": ["7", 0],
                    "vae": ["4", 2],
                    "pixels": ["10", 0],
                    "mask": ["11", 0],
                    # Required by current ComfyUI: keep the unmasked latent as a
                    # noise mask so only the masked region is denoised.
                    "noise_mask": True,
                },
            },
            "8": {
                "class_type": "VAEDecode",
                "inputs": {"samples": ["3", 0], "vae": ["4", 2]},
            },
            "9": {
                "class_type": "SaveImage",
                "inputs": {"filename_prefix": filename_prefix, "images": ["8", 0]},
            },
        }
    return {
        "3": {
            "class_type": "KSampler",
            "inputs": _sampler_inputs(
                params=params,
                seed=seed,
                default_denoise=1,
                default_steps=24,
                latent_ref=["5", 0],
                model_ref=["4", 0],
                positive_ref=["6", 0],
                negative_ref=["7", 0],
            ),
        },
        "4": {
            "class_type": "CheckpointLoaderSimple",
            "inputs": {
                "ckpt_name": checkpoint_name,
            },
        },
        "5": {
            "class_type": "EmptyLatentImage",
            "inputs": {
                "batch_size": 1,
                "height": int(params.get("height", 1024)),
                "width": int(params.get("width", 768)),
            },
        },
        "6": {
            "class_type": "CLIPTextEncode",
            "inputs": {
                "clip": ["4", 1],
                "text": positive_prompt,
            },
        },
        "7": {
            "class_type": "CLIPTextEncode",
            "inputs": {
                "clip": ["4", 1],
                "text": negative_prompt,
            },
        },
        "8": {
            "class_type": "VAEDecode",
            "inputs": {
                "samples": ["3", 0],
                "vae": ["4", 2],
            },
        },
        "9": {
            "class_type": "SaveImage",
            "inputs": {
                "filename_prefix": filename_prefix,
                "images": ["8", 0],
            },
        },
    }


def _stable_seed(prompt_id: str) -> int:
    return int(prompt_id[:8], 16)


def _resolve_seed(params: dict | None, prompt_id: str) -> int:
    """Use an explicit §6.2 ``seed`` param when provided (so a refine can fix
    or vary the seed deterministically), otherwise derive a stable seed."""
    params = params or {}
    seed = params.get("seed")
    if seed is not None:
        try:
            return int(seed)
        except (TypeError, ValueError):
            pass
    return _stable_seed(prompt_id)


def _upload_input_asset(client: httpx.Client, base_url: str, asset_path: Path) -> str:
    """Upload a source image or a standalone mask image into ComfyUI's input
    space. Both go through ``/upload/image``; an inpaint mask is then read from
    its red channel by ``LoadImageMask`` in the workflow graph (spec §5.11)."""
    with asset_path.open("rb") as file_handle:
        response = client.post(
            f"{base_url}/upload/image",
            files={"image": (asset_path.name, file_handle, "application/octet-stream")},
            data={"type": "input", "overwrite": "true"},
        )
    response.raise_for_status()
    payload = response.json()
    return str(payload.get("name") or asset_path.name)


def _wait_for_history(client: httpx.Client, base_url: str, prompt_id: str, context: AdapterContext) -> dict:
    for _ in range(120):
        response = client.get(f"{base_url}/history/{prompt_id}")
        response.raise_for_status()
        payload = response.json()
        history = payload.get(prompt_id)
        if history and history.get("outputs"):
            if context.report_progress:
                context.report_progress(85, "Downloading generated images")
            return history
        time.sleep(1)
    raise RuntimeError("ComfyUI did not finish within the expected timeout.")


def _download_output_images(client: httpx.Client, base_url: str, history: dict) -> list[dict[str, bytes | str]]:
    output_images: list[dict[str, bytes | str]] = []
    outputs = history.get("outputs") or {}
    for node_output in outputs.values():
        for image in node_output.get("images", []):
            query = urlencode(
                {
                    "filename": str(image.get("filename") or ""),
                    "subfolder": str(image.get("subfolder") or ""),
                    "type": str(image.get("type") or "output"),
                }
            )
            response = client.get(f"{base_url}/view?{query}")
            response.raise_for_status()
            output_images.append({"filename": str(image.get("filename") or "output.png"), "content": response.content})
    return output_images
