from __future__ import annotations

import re
from pathlib import Path

import httpx

from core.generation.adapters.common import AdapterContext, AdapterExecutionResult, GeneratedArtifact
from core.models.schemas import Modality


def adapter_name() -> str:
    return "gpt_sovits"


def execute(context: AdapterContext) -> AdapterExecutionResult:
    if not context.health_check:
        raise RuntimeError("GPT-SoVITS health check URL is missing.")
    reference_audio = context.source_asset_path or _find_reference_audio(context.project_dir)
    if reference_audio is None:
        raise RuntimeError("GPT-SoVITS requires a reference audio file under assets/audio or models.")
    base_url = context.health_check.removesuffix("/docs").rstrip("/")
    language = _detect_language(context.job.prompt)
    payload = {
        "text": context.job.prompt,
        "text_lang": language,
        "ref_audio_path": str(reference_audio.resolve()),
        "prompt_text": "",
        "prompt_lang": language,
        "text_split_method": "cut5",
        "media_type": "wav",
        "streaming_mode": False,
    }

    with httpx.Client(timeout=120.0) as client:
        if context.report_progress:
            context.report_progress(25, "Submitting TTS request")
        response = client.post(f"{base_url}/tts", json=payload)
        response.raise_for_status()

    artifact = GeneratedArtifact(
        modality=Modality.VOICE,
        asset_type="voice",
        title=context.job.title,
        filename=f"{context.job.project_id}-{context.job.id[:8]}.wav",
        description=f"Generated by GPT-SoVITS using reference audio {reference_audio.name}.",
        content=response.content,
    )
    return AdapterExecutionResult(artifacts=[artifact], metadata={"reference_audio": str(reference_audio)})


def _find_reference_audio(project_dir: Path) -> Path | None:
    candidate_roots = [project_dir / "assets" / "audio", project_dir / "models"]
    for root in candidate_roots:
        if not root.exists():
            continue
        for extension in ("*.wav", "*.mp3", "*.flac", "*.m4a", "*.ogg"):
            matches = sorted(root.rglob(extension))
            if matches:
                return matches[0]
    return None


def _detect_language(text: str) -> str:
    if re.search(r"[\u3040-\u30ff]", text):
        return "ja"
    if re.search(r"[\u4e00-\u9fff]", text):
        return "zh"
    return "en"
