from __future__ import annotations

from pathlib import Path

from core.generation.adapters.common import AdapterContext, AdapterExecutionResult, GeneratedArtifact
from core.models.schemas import Modality


def adapter_name() -> str:
    return "stable-audio-tools"


def execute(context: AdapterContext) -> AdapterExecutionResult:
    if not context.health_check:
        raise RuntimeError("stable-audio-tools health check URL is missing.")

    try:
        from gradio_client import Client, handle_file
    except ImportError as exc:  # pragma: no cover - environment specific
        raise RuntimeError("gradio_client is required to call stable-audio-tools.") from exc

    base_url = context.health_check.rstrip("/")
    client = Client(base_url)
    init_audio = handle_file(str(context.source_asset_path)) if context.source_asset_path else None
    use_inpaint = context.mask_asset_path is not None and context.source_asset_path is not None
    inpaint_audio = handle_file(str(context.mask_asset_path)) if use_inpaint else None

    if context.report_progress:
        context.report_progress(20, "Submitting stable-audio-tools request")
    result = client.predict(
        context.job.prompt,
        "",
        0,
        30,
        6.0,
        100,
        0,
        -1,
        "dpmpp-3m-sde",
        0.03,
        1000,
        1.0,
        0.0,
        1.0,
        0.0,
        "wav",
        "output.wav",
        True,
        init_audio,
        0.1,
        0.0,
        30.0,
        inpaint_audio,
        api_name="/generate",
    )
    output_path = _resolve_output_path(result)
    if context.report_progress:
        context.report_progress(85, "Saving generated audio")
    artifact = GeneratedArtifact(
        modality=Modality.MUSIC,
        asset_type="music",
        title=context.job.title,
        filename=f"{context.job.project_id}-{context.job.id[:8]}{output_path.suffix or '.wav'}",
        description="Generated by stable-audio-tools.",
        source_path=output_path,
    )
    return AdapterExecutionResult(artifacts=[artifact], metadata={"backend": "stable-audio-tools"})


def _resolve_output_path(payload: object) -> Path:
    if isinstance(payload, str):
        return Path(payload)
    if isinstance(payload, dict):
        path = payload.get("path") or payload.get("name")
        if isinstance(path, str):
            return Path(path)
    if isinstance(payload, (list, tuple)):
        for item in payload:
            try:
                return _resolve_output_path(item)
            except RuntimeError:
                continue
    raise RuntimeError("stable-audio-tools did not return a downloadable audio file.")
