from __future__ import annotations

from pathlib import Path

from core.generation.adapters.common import AdapterContext, AdapterExecutionResult, GeneratedArtifact
from core.models.schemas import Modality


def adapter_name() -> str:
    return "voxcpm"


def execute(context: AdapterContext) -> AdapterExecutionResult:
    if not context.health_check:
        raise RuntimeError("VoxCPM health check URL is missing.")

    try:
        from gradio_client import Client, handle_file
    except ImportError as exc:  # pragma: no cover - environment specific
        raise RuntimeError("gradio_client is required to call the VoxCPM worker.") from exc

    base_url = context.health_check.rstrip("/")
    if context.report_progress:
        context.report_progress(15, "Connecting to VoxCPM")

    client = Client(base_url)
    prompt_text = context.job.prompt.strip()
    control_instruction = context.job.summary.strip()
    reference_wav = handle_file(str(context.source_asset_path)) if context.source_asset_path else None
    use_prompt_text = bool(context.source_asset_path)
    prompt_text_value = control_instruction if use_prompt_text else ""

    if context.report_progress:
        context.report_progress(35, "Submitting TTS request")
    result = client.predict(
        prompt_text,
        control_instruction if not use_prompt_text else "",
        reference_wav,
        use_prompt_text,
        prompt_text_value,
        2.0,
        False,
        False,
        10,
        api_name="/generate",
    )

    output_path = _resolve_output_path(result)
    if context.report_progress:
        context.report_progress(85, "Saving generated audio")
    artifact = GeneratedArtifact(
        modality=Modality.VOICE,
        asset_type="voice",
        title=context.job.title,
        filename=f"{context.job.project_id}-{context.job.id[:8]}{output_path.suffix or '.wav'}",
        description="Generated by VoxCPM.",
        source_path=output_path,
    )
    return AdapterExecutionResult(artifacts=[artifact], metadata={"backend": "voxcpm"})


def _resolve_output_path(payload: object) -> Path:
    if isinstance(payload, str):
        return Path(payload)
    if isinstance(payload, dict):
        path = payload.get("path") or payload.get("name")
        if isinstance(path, str):
            return Path(path)
    if isinstance(payload, (list, tuple)):
        for item in payload:
            try:
                return _resolve_output_path(item)
            except RuntimeError:
                continue
    raise RuntimeError("VoxCPM did not return a downloadable audio file.")
